# PostgreSQL replica configuration for Streaming Replication
wal_level = replica
max_wal_senders = 10
wal_keep_size = 512
max_replication_slots = 10
listen_addresses = '*'

# Replica settings
hot_standby = on            # allow read-only queries on replica